config/routes.rb
Itaste::Application.routes.draw do

  root :to => "wines#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'signout', to: 'sessions#destroy', as: 'signout'
  get '/sitemap', to: 'sitemap#index'

  resources :users do
    get '/notes', to: "wines#notes"
    resources :lists, only: [:index, :show]
  end

  resources :wines do
    collection do
      get :create_wine, as: :create_wine
      get :facebook_places
    end
  end
  resources :producers, only: [:index, :show]
  resources :foods, only: [:index]
  resources :regions, only: [:index]
  resources :grapes, only: [:index]
  resources :places, only: [:index]
  resources :photos do
    put :set_feature
  end

  resources :lists

  get '/terms', to: 'welcome#terms'
  get '/privacy', to: 'welcome#privacy'

end

app/views/shared/_facebook_comments.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=<%= OMNIAUTH_CONFIG['facebook']['app_id'] %>";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-comments" data-href="<%= "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>" data-num-posts="5" data-colorscheme="dark"></div>

app/views/shared/_footer.html.slim
.footer
  .container
    .row
      .span6.logo-vt
        a.brand href="#"
          span 品味
          span.cl-blue 筆記
        span.coppy_right
          p @2012 All Rights Reserved.
      .span4
        = render 'shared/facebook_fanpage'
      .span2
        ul.nav.nav-list
          li.nav-header 追蹤品味筆記
          li
            a href="https://twitter.com/itastetw"
              i.twitter
              | Twitter
          li
            a href="https://www.facebook.com/pages/itastetw/561034483913153"
              i.facebook
              | Facebook
          li
            a href="http://blog.itaste.tw"
              i.dd
              | 部落格
/! end footer

app/views/shared/_navbar.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      a.brand href="/"
        span 品味
        span.cl-blue 筆記
      .nav-collapse
        ul.nav.pull-right
          - if current_user
            li= link_to '我的筆記', user_notes_path(current_user)
            li.divider-vertical
            li
              = avatar_image(current_user, :thumb, 'nav-avatar')
            li.dropdown
              = link_to "#", data: { toggle: 'dropdown', class: 'dropdown-toggle' } do
                | #{current_user.username}
                b.caret
              ul.dropdown-menu
                li= link_to user_notes_path(current_user) do
                  i.icon-dashboard
                  | 我的筆記
                li.divider
                li= link_to signout_path, :id => "sign_out", method: :delete do
                  i.icon-off
                  | 登出
          - else
            li
              = link_to '登入', user_omniauth_authorize_path(:facebook), id: 'signin-btn-in-nav'
              ' 來建立專屬於自己的品酒筆記

app/views/shared/_share_tools.html.erb
<div class="sharing">

  <h3>何不分享給朋友：</h3>
  <!-- Place this tag where you want the +1 button to render. -->
  <div class="g-plusone" data-size="medium"></div>

  <!-- Place this tag after the last +1 button tag. -->
  <script type="text/javascript">
    window.___gcfg = {lang: 'zh-TW'};

    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
  </script>

  <a href="https://twitter.com/share" class="twitter-share-button" data-lang="zh-tw">推文</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=477105525665881";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <div class="fb-like" data-href="<%= url %>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false" data-colorscheme="dark"></div>

</div>