config/routes.rb
Itaste::Application.routes.draw do

  root :to => "wines#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'signout', to: 'sessions#destroy', as: 'signout'
  get '/sitemap', to: 'sitemap#index'

  resources :users do
    get '/notes', to: "wines#notes"
    resources :lists, only: [:index, :show]
  end

  resources :wines do
    collection do
      get :create_wine, as: :create_wine
      get :facebook_places
    end
  end
  resources :producers, only: [:index, :show]
  resources :foods, only: [:index]
  resources :regions, only: [:index]
  resources :grapes, only: [:index]
  resources :places, only: [:index]
  resources :photos do
    put :set_feature
  end

  resources :lists

  get '/terms', to: 'welcome#terms'
  get '/privacy', to: 'welcome#privacy'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :wine_id, :image, :remote_image_url
  belongs_to :wine
  mount_uploader :image, ImageUploader
  #process_in_background :image
  #store_in_background :image

  def self.feature_photo(version = :normal)
    photo = where(is_feature: true).first || self.first
    if photo.present?
      photo.image_url(version)
    else
      "fallback/" + [version.to_s, "default.png"].compact.join('_')
    end

  end

  def set_as_feature
    self.set_as_feature_and_unset_others
  end

  def set_as_feature_and_unset_others
    self.wine.photos.update_all(is_feature: false)
    self.update_attribute(:is_feature, true)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  config.relative_url_root = ""
  def create
    @photo = Photo.create(params[:photo])
  end

  def set_feature
    @photo = Photo.find(params[:photo_id])
    @last_feature_photo = @photo.wine.photos.where(is_feature: true).first
    @photo.set_as_feature
  end

  def destroy
    @photo = Photo.find(params[:id])
    @id = @photo.id
    @photo.delay.destroy
  end
end

app/views/photos/_photo.html.slim
li class="photo-#{photo.id}-block"
  = image_tag(photo.image_url(:normal), class: "border-rd4 photo-#{photo.id} #{'feature' if photo.is_feature?}")
  .functions
    span.pull-left id='set-feature-#{photo.id}'= link_to '設定為特色圖片', photo_set_feature_path(photo), method: :put, remote: true
    span class='pull-right' id='photo-#{photo.id}-remove'= link_to '移除', photo_path(photo), method: :delete, confirm: '確定要刪除這張照片？', remote: true

app/views/photos/_photo_modal.html.slim
li class="photo-#{photo.id}-block"
  = image_tag(photo.image_url(:thumb), class: "border-rd4 photo-#{photo.id}")
  .functions
    = link_to '設定為特色圖片', photo_set_feature_path(photo), method: :put, remote: true

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert("照片上傳失敗: <%= j @photo.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#upload-photo-ul ul.thumbnails").append("<%= j render 'photo', :photo => @photo %>");
  $("#photos-in-modal").append("<%= j render 'photo_modal', :photo => @photo %>");
<% end %>

app/views/photos/destroy.js.erb
$("li.photo-<%= @id %>-block").fadeOut(300, function() { $(this).remove(); })

app/views/photos/set_feature.js.erb
$("img").removeClass('feature')
$("img.photo-<%= @photo.id %>").addClass('feature')