config/routes.rb
Itaste::Application.routes.draw do

  root :to => "wines#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'signout', to: 'sessions#destroy', as: 'signout'
  get '/sitemap', to: 'sitemap#index'

  resources :users do
    get '/notes', to: "wines#notes"
    resources :lists, only: [:index, :show]
  end

  resources :wines do
    collection do
      get :create_wine, as: :create_wine
      get :facebook_places
    end
  end
  resources :producers, only: [:index, :show]
  resources :foods, only: [:index]
  resources :regions, only: [:index]
  resources :grapes, only: [:index]
  resources :places, only: [:index]
  resources :photos do
    put :set_feature
  end

  resources :lists

  get '/terms', to: 'welcome#terms'
  get '/privacy', to: 'welcome#privacy'

end

app/models/wine.rb
#encoding: utf-8
class Wine < ActiveRecord::Base
  attr_accessible :alcohol, :appearance, :name, :nose, :price, :producer_id, :serving_temperature_from, :serving_temperature_to, :suggested_glass, :taste, :vintage, :when, :wine_type, :user_id, :place_id, :opinion, :producer_name, :food_ids, :food_tokens, :grape_tokens, :rating, :region_name, :region_id, :complete, :place_name, :place_attributes
  attr_reader :food_tokens, :grape_tokens
  include ActiveModel::Dirty

  is_impressionable counter_cache: true

  belongs_to :user
  belongs_to :producer
  belongs_to :region
  belongs_to :place
  has_many :wine_grape_ship
  has_many :grapes, through: :wine_grape_ship
  has_many :wine_badge_ship
  has_many :badges, through: :wine_badge_ship
  has_many :wine_food_ship
  has_many :foods, through: :wine_food_ship
  has_many :photos
  has_many :wine_list_ship
  has_many :lists, through: :wine_list_ship
  accepts_nested_attributes_for :place

  validates_presence_of :name
  validates_presence_of :wine_type
  validates_inclusion_of :rating, in: 1..100

  scope :uncomplete, where(complete: false)
  scope :completed, where(complete: true)
  scope :sitemap, :select => 'id, name, created_at, updated_at', :limit => 4999

  before_update :find_or_create_place

  delegate :facebook_id, to: :place, allow_nil: true, prefix: true

  WINE_TYPE = %w{ red_wine white_wine champagne sparkling_wine }
  GLASS_TYPE = %w{ bordeaux_red_wine burgundy_red_wine bordeaux_white_wine burgundy_white_wine sparkling_wine dessert_wine }

  def self.find_uncomplete_or_create_without_validation(user)
    wine = user.wines.uncomplete.first || self.create_without_validation(user)
  end

  def other_wines(count=4)
    ids = self.user.wines.map(&:id)
    ids.delete self.id
    Wine.find(ids).sample(count)
  end

  def serving_temperature_range
    serving_temperature_from.to_s + "度 - " + serving_temperature_to.to_s + "度"
  end

  def producer_name
    producer.try(:name)
  end

  def producer_name=(name)
    self.producer = Producer.find_or_create_by_name(name) if name.present?
  end

  def place_name
    place.try(:name)
  end

  def place_name=(name)
    self.place = Place.find_or_create_by_name(name) if name.present?
  end

  def region_name
    region.try(:name)
  end

  def region_name=(name)
    self.region = Region.find_or_create_by_name(name) if name.present?
  end

  def food_tokens=(tokens)
    self.food_ids = Food.ids_from_tokens(tokens)
  end

  def grape_tokens=(tokens)
    self.grape_ids = Grape.ids_from_tokens(tokens)
  end

  private

  def self.create_without_validation(user)
    wine = user.wines.build
    wine.save(validate: false)
    wine
  end

  def find_or_create_place
    self.place = Place.where(facebook_id: self.place.facebook_id).first_or_create do |p|
      p.name = self.place.name
      p.lat = self.place.lat
      p.lon = self.place.lon
    end
  end

end

app/controllers/wines_controller.rb
#encoding: utf-8
class WinesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :notes]
  load_and_authorize_resource except: [:notes, :create_wine, :facebook_places]

  def show
    @wine = Wine.find(params[:id])
  end

  def index
    if params[:format] == 'json'
      @wines = @wines.completed.order(:name).where("name like ?", "%#{params[:term]}%")
    else
      @wines = @wines.completed.order('created_at desc').paginate(page: params[:page])
    end
    respond_to do |format|
      format.html
      format.json { render :json => @wines.map(&:name) }
    end
  end

  def notes
    @user = User.find(params[:user_id])
    @wines = @user.wines.completed.paginate(page: params[:page], per_page: 20)
    @lists = @user.lists
  end

  def create_wine
    @wine = Wine.find_uncomplete_or_create_without_validation(current_user)
    redirect_to edit_wine_path(@wine)
  end

  def edit
    @wine = Wine.find(params[:id])
    @wine.place ||= @wine.build_place
    redirect_to @wine, notice: '你沒有權限編輯這個項目' unless current_user.has_permission?(@wine)
  end

  def update
    @wine = Wine.find(params[:id])
    redirect_to @wine, notice: '你沒有權限編輯這個項目' unless current_user.has_permission?(@wine)

    if @wine.complete?
      if @wine.update_attributes(params[:wine])
        redirect_to @wine, notice: "成功更新了#{@wine.name}"
      else
        render :edit
      end
    else
      if @wine.update_attributes(params[:wine])
        current_user.delay.post_to_facebook(wine_url(@wine), @wine.place_facebook_id)
        redirect_to @wine, notice: "成功建立了#{@wine.name}"
      else
        render :edit
      end
    end
  end

  def destroy
    @wine = Wine.find(params[:id])
    redirect_to @wine, notice: '你沒有權限編輯這個項目' unless current_user.has_permission?(@wine)

    name = @wine.name
    @wine.destroy
    redirect_to user_notes_path(current_user), notice: "成功刪除了#{name}"
  end

end

app/helpers/wines_helper.rb
#encoding: utf-8
module WinesHelper

  def collection_for_suggested_glass
    Wine::GLASS_TYPE.map { |value|
      [t(value, scope: 'activerecord.options.suggested_glasses'), value]
    }
  end

  def collection_for_wine_type
    Wine::WINE_TYPE.map { |value|
      [t(value, scope: 'activerecord.options.wine_types'), value]
    }
  end

  def set_feature_link(photo)
    content_tag(:span, class: 'pull-left', id: "set-feature-#{photo.id}") do
      link_to "設定為特色圖片", photo_set_feature_path(photo), method: :put, remote: true
    end
  end

  def feature_photo(wine)
    if wine.photos.feature_photo == "fallback/normal_default.png"
      "http://#{request.host+request.fullpath+@wine.photos.feature_photo}"
    else
      wine.photos.feature_photo
    end
  end

end

app/views/wines/_form.html.slim
.box-form.widget
  .widget-content
    .row-fluid
      = render 'photos_form'
    = simple_form_for @wine, html: { class: 'form-horizontal' } do |f|
      .row-fluid
        .span6
          .title
            h3 酒的基本資料
          = f.input :name, label: "酒名", placeholder: "例如：Romanee-Conti", input_html: { class: 'wine-name-picker span12', data: { autocomplete_source: wines_path(format: :json) } }
          = f.input :wine_type, label: "種類", collection: collection_for_wine_type, :as => :radio_buttons, :item_wrapper_class => 'inline'
          = f.input :grape_tokens, label: "葡萄品種", as: :string, input_html: { id: 'grape-token-input', data: { load: @wine.grapes } }, placeholder: '例如：Cabernet Sauvignon'
          = f.input :vintage, label: "年份", as: :select, collection: 1950..Time.now.year, include_blank: false
          = f.input :alcohol, label: "酒精濃度", input_html: { class: 'span12' }
          = f.input :producer_name, label: "酒莊", input_html: { class: 'producer-picker span12', data: { autocomplete_source: producers_path(format: :json) } }
          = f.input :region_name, label: "產區", input_html: { class: 'region-picker span12', data: { autocomplete_source: regions_path(format: :json) } }
        .span6
          .title
            h3 個人體驗
          = f.input :suggested_glass, label: "適用酒杯", collection: collection_for_suggested_glass, :as => :select, :item_wrapper_class => 'inline', include_blank: false
          = f.input :food_tokens, label: "搭配餐點", as: :string, input_html: { class: 'span6', id: "food-token-input", data: { load: @wine.foods } }
          .control-group
            label.control-label 適飲溫度
            .controls
              #serving-temperature-range-ui.span12.ui-slider.ui-slider-horizontal.ui-widget.ui-widget-content.ui-corner-all
              span#serving_temperature_range.help-inline
          = f.input :price, label: "價格"
          = f.input :when, label: "品酒日期", as: :string, input_html: { class: 'date-picker' }
          = f.simple_fields_for :place do |p|
            = p.input :name, label: '品酒地點', input_html: { class: 'place-picker', data: { autocomplete_source: "https://graph.facebook.com/search?access_token=#{current_user.facebook_token}&type=place&q=" } }
            = p.input :lat, as: :hidden
            = p.input :lon, as: :hidden
            = p.input :facebook_id, as: :hidden
          = f.input :serving_temperature_from, as: :hidden, input_html: { id: 'serving_temperature_from' }
          = f.input :serving_temperature_to, as: :hidden, input_html: { id: 'serving_temperature_to' }
          = f.input :complete, as: :hidden, input_html: { value: 'true' }
      hr
      .row-fluid
        .span12
          = f.input :opinion, label: "想法", input_html: { class: 'span12', rows: 20 }, hint: "你對這隻酒的感想、記錄會是你對這支酒的最佳筆記"
          = f.input :rating, label: '我的評分', :item_wrapper_class => 'inline', hint: '上限為100分', input_html: { id: 'rating-value'}
      .form-actions
        = f.submit "送出", class: 'btn btn-primary'
        = submit_tag '取消', :type => :reset, :class => 'btn btn-danger'

app/views/wines/_photos_form.html.slim
.span12
  ul#upload-photo-ul
    h3.title 上傳圖片(上傳這支酒的代表性圖片，可上傳多張)
    ul.thumbnails
      li
        = link_to(image_tag(asset_path('photo-placeholder.jpg'), id: 'upload-photo-placeholder'), "#upload-modal", id: 'upload-photo-link', data: { toggle: 'modal'})
      = render @wine.photos
  #upload-modal.modal.hide.fade
    .modal-header
      buton.close type='button' data-dismiss='modal' aria-hidden='true' &times;
      h3 上傳照片
    .modal-body
      ul#photos-in-modal
        - @wine.photos.each do |photo|
          = render 'photos/photo_modal', :photo => photo
    .modal-footer
      .upload-form
        = form_for @wine.photos.build do |f|
          = f.file_field :image, multiple: true, name: "photo[image]"
          = f.hidden_field :wine_id, valud: @wine.id
      .clearfix
      .upload-progress

        script#template-upload type="text/x-tmpl"
          .upload
            | {%=o.name%}
            .progress.progress-success.progress-striped.active
              .bar style="width: 0%;"

      .clearfix
      hr
      span 上傳檔案限制為 5MB 以下之 jpg, jpeg, png 格式圖片。
      br
      span 選擇上傳照片時按住 Shift 不放可選擇多張。

app/views/wines/edit.html.slim
.row
  .span12
    = render 'form'

app/views/wines/index.html.slim
- set_meta_tags :title => '在品味筆記上所有的好品味', :description => '品味好酒、品味好書、品味好音樂、品味好電影、品味生活，然後與朋友分享，品味人生'
- set_meta_tags :open_graph => { title: '在品味筆記上所有的好品味', type: 'Website', url: "http://#{request.host+request.fullpath}", image: "http://#{request.host}/assets/logo-128.png" }
.row
  .box-wrapper.span12
    .row
      .title.span12
        h1.pull-left 大家都在喝
        = link_to create_wine_wines_path, class: 'btn btn-primary pull-right' do
          i.icon-glass
          | 寫筆記
    ul.thumbnails.thumbnails-vertical
      - @wines.each do |wine|
        li.wine.span6
          .thumbnail.border-radius-top
            .avatar
              = link_to avatar_image(wine.user, :thumb, 'wine-avatar pull-left'), user_notes_path(wine.user)
              span #{link_to wine.user.username, user_notes_path(wine.user)}
              span.pull-right= l (wine.when || wine.updated_at), format: :mini
              .clearfix
            .bg-thumbnail-img
              = link_to image_tag(wine.photos.feature_photo(:normal), class: 'border-rd4', alt: wine.name), wine
            .thumbnail-content-left
              h2= link_to wine.name, wine
              = simple_format wine.opinion
          .box.border-radius-bottom
            p
              span.pull-left= t wine.wine_type, scope: 'activerecord.options.wine_types'
              span.number-view.pull-right
    .row
      .span12
        .pull-right
          = will_paginate(@wines)

app/views/wines/new.html.slim
.row
  .sidebar-content.span3
    = render 'photos_form'
  .span9
    = render 'form'

app/views/wines/notes.html.slim
- set_meta_tags :title => "#{@user.username}的筆記", :description => '品味好酒、品味好書、品味好音樂、品味好電影、品味生活，然後與朋友分享，品味人生'
- set_meta_tags :open_graph => { title: "#{@user.username}的筆記", type: 'Website', url: "http://#{request.host+request.fullpath}", image: "http://#{request.host}/assets/fallback/normal_default.png" }

.row
  .box-wrapper.span12
    .row
      .title.span12
        h1.pull-left #{@user.username}的品味筆記
    ul.thumbnails.thumbnails-horizontal
      - @wines.each do |wine|
        li.span3
          .thumbnail.border-radius-top
            .avatar
              = avatar_image(@user, :thumb, 'wine-avatar pull-left')
              span.pull-right= l (wine.when || wine.updated_at), format: :mini
              .clearfix
            .bg-thumbnail-img
              = link_to image_tag(wine.photos.feature_photo(:normal), class: 'border-rd4', alt: wine.name), wine
            h5= link_to wine.name, wine
          .box.border-radius-bottom
            p
              span.pull-left= t wine.wine_type, scope: 'activerecord.options.wine_types'
              span.number-view.pull-right
      - if @user == current_user
        li.span3
            .thumbnail.border-radius-top
              .bg-thumbnail-img
                = link_to image_tag(asset_path('fallback/normal_default.png')), create_wine_wines_path
              h5= link_to '新增一則筆記', create_wine_wines_path
    .row
      .span12
        .pull-right
          = will_paginate(@wines)
  /.span3
    /.widget
      /.widget-content
        /h3.title #{@user.username}的酒單
        /- if @user == current_user
          /= link_to "新增酒單", new_list_path, class: 'btn btn-primary span2'
        /.clearfix
        /ul.wine-list
          /- @lists.each do |list|
            /= link_to "#{list.name}(#{list.size})支酒", list

app/views/wines/show.html.slim
- set_meta_tags :title => @wine.name, :description => @wine.opinion || "#{@wine.user.username}在品味筆記上對#{@wine.name}的筆記"
- set_meta_tags :open_graph => { title: @wine.name, type: 'itastetw:wine', url: "http://#{request.host+request.fullpath}", image: feature_photo(@wine), message: @wine.opinion, place: @wine.place_facebook_id }

#wine-page.row
  .box-wrapper.span9
    .row
      .box-content-widget.span9
        .row
          .title.bg-title.span9
            h1.show-title.pull-left= @wine.name
            - if can? :update, @wine
              .actions.pull-right
                = link_to '編輯', edit_wine_path(@wine)
                '
                ' |
                '
                = link_to '刪除', wine_path(@wine), method: :delete, confirm: "確認要刪除#{@wine.name}嗎？他是一瓶好酒啊"
        .widget
          .widget-content
            .row-fluid
              .span7
                = image_tag(@wine.photos.feature_photo(:large), class: 'border-rd4', id: 'feature-photo')
              .span5.wine-info
                ul.wine-info-list
                  - if @wine.vintage
                    li
                      .overflow-hidden
                        span.wine-property-label 年份
                        span.wine-property= @wine.vintage
                  - if @wine.producer
                    li
                      .overflow-hidden
                        span.wine-property-label 酒莊
                        span.wine-property= @wine.producer_name
                  - if @wine.region
                    li
                      .overflow-hidden
                        span.wine-producer-label 產地
                        span.wine-property= @wine.region_name
                  - if @wine.serving_temperature_from || @wine.serving_temperature_to
                    li
                      .overflow-hidden
                        span.wine-producer-label 適飲溫度
                        span.wine-property= @wine.serving_temperature_range
                  - if @wine.suggested_glass
                    li
                      .overflow-hidden
                        span.wine-producer-label 適用酒杯
                        span.wine-property= t(@wine.suggested_glass, scope: 'activerecord.options.suggested_glasses')
                  - if @wine.price
                    li
                      .overflow-hidden
                        span.wine-producer-label 價格
                        span.wine-property= number_to_currency @wine.price, precision: 0
                  - if @wine.foods.count != 0
                    li
                      .overflow-hiddem
                        span.wine-food-label 搭配食物
                        span.wine-food-label-tags
                          - @wine.foods.each do |food|
                            span.label.label-info.food-tag= food.name
                  - if @wine.place
                    li
                      .overflow-hiddem
                        span.wine-place-label 品味地點
                        span.wine-place= @wine.place_name
                span.pull-right.user-rating #{@wine.rating}
                .clearfix
            .row-fluid
              .span12
                .wine-photos
                  - @wine.photos.each do |photo|
                    = image_tag(photo.image_url(:thumb), class: 'border-rd4 wine-photo', id: "wine-photo-#{photo.id}", data: { src: photo.image_url(:large) })
            hr
            - if @wine.opinion.present?
              = simple_format @wine.opinion
            .row-fluid
              .pull-right
                = render partial: 'shared/share_tools', locals: { url: wine_url(@wine) }
              .clearfix
        .widget
          .widget-content
            = render 'shared/facebook_comments'
  .sidebar-content.span3
    .row
      .list-menu.box-wrapper.span3
        .row
          .title.bg-title.span3
            h3 其他筆記
        ul.thumbnails.thumbnails-horizontal
          - @wine.other_wines(4).each do |wine|
            li.span3
              .thumbnail.border-radius-top
                .bg-thumbnail-img
                  = link_to image_tag(wine.photos.feature_photo(:normal), class: 'border-rd4', alt: wine.name), wine_path(wine)
                h5= link_to wine.name, wine_path(wine)
              .box.border-radius-bottom
                p
                  span.title_torrent.pull-left= t wine.wine_type, scope: 'activerecord.options.wine_types'